#!/usr/bin/env python3
"""Rasterise Inter (OFL) into anti-aliased VLW fonts for LovyanGFX.

The panel is only ~230 ppi, and the bundled Adafruit-GFX fonts are 1-bit, so
text shows stair-steps. VLW glyphs carry 8-bit alpha, which LovyanGFX blends
onto the sprite. Output: ../src/fonts_gen.h (arrays loaded by ui.cpp).

    python3 tools/gen_fonts.py        # needs Pillow
"""
import struct
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).parent
TTF = HERE / "Inter.ttf"
OUT = HERE.parent / "src" / "fonts_gen.h"

# name, weight, pixel size
FONTS = [
    ("b44", 700, 44), ("b36", 700, 36), ("b30", 700, 30), ("b24", 700, 24),
    ("b18", 700, 18), ("s12", 600, 13), ("r17", 400, 17),
]
CHARS = [chr(c) for c in range(0x20, 0x7F)]


def build(weight, size):
    f = ImageFont.truetype(str(TTF), size)
    f.set_variation_by_axes([min(32, max(14, size)), weight])
    glyphs, bitmaps = [], []
    for ch in CHARS:
        adv = round(f.getlength(ch))
        l, t, r, b = f.getbbox(ch, anchor="ls")
        w, h = max(0, r - l), max(0, b - t)
        data = b""
        if ch != " " and w and h:
            im = Image.new("L", (w, h), 0)
            ImageDraw.Draw(im).text((-l, -t), ch, font=f, fill=255, anchor="ls")
            data = im.tobytes()
        else:
            w = h = 0
        glyphs.append((ord(ch), h, w, adv, -t if h else 0, l if w else 0))
        bitmaps.append(data)
    asc = -f.getbbox("d", anchor="ls")[1]
    desc = f.getbbox("p", anchor="ls")[3]
    out = struct.pack(">6i", len(glyphs), 11, size, 0, asc, desc)
    for g in glyphs:
        out += struct.pack(">7i", *g, 0)
    return out + b"".join(bitmaps)


with OUT.open("w") as fh:
    fh.write("#pragma once\n// Generated by tools/gen_fonts.py (Inter, SIL OFL). Do not edit.\n"
             "#include <stdint.h>\n")
    for name, wt, sz in FONTS:
        blob = build(wt, sz)
        print(name, len(blob), "bytes")
        fh.write(f"static const uint8_t font_{name}[] = {{\n")
        for i in range(0, len(blob), 24):
            fh.write(",".join(str(x) for x in blob[i:i + 24]) + ",\n")
        fh.write("};\n")
